### PR TITLE
(WiP) Feature/impl display

### PR DESCRIPTION
**Pull request by mgill25**

### CODE REVIEW

**Comment by darnir** [comment]
Can you please merge my Makefile updates into the branch first?

**Comment by mgill25** [comment]
@darnir where are the updates? I don't see them in master.

**Comment by darnir** [comment]
PR #1

**Comment by darnir** [comment]
There seem to be conflicts, can you resolve them and update the branch?

**Comment by mgill25** [comment]
@darnir I think we've gotten confused b/w github and gitlab. Lets just use gitlab for everything and ignore this. (that's what I'm basing my branches on)

**Pull request closed without merging**
